/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'propertyId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const PropertyStatus = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Nat,
  'description' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func(
      [
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getPropertiesByStatus' : IDL.Func(
      [PropertyStatus],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertyById' : IDL.Func([IDL.Nat], [Property], ['query']),
  'searchProperties' : IDL.Func(
      [IDL.Text, IDL.Opt(PropertyType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'seedProperties' : IDL.Func([], [], []),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'updateProperty' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        PropertyStatus,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'propertyId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const PropertyStatus = IDL.Variant({
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Nat,
    'description' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func(
        [
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getPropertiesByStatus' : IDL.Func(
        [PropertyStatus],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertyById' : IDL.Func([IDL.Nat], [Property], ['query']),
    'searchProperties' : IDL.Func(
        [IDL.Text, IDL.Opt(PropertyType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'seedProperties' : IDL.Func([], [], []),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'updateProperty' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          PropertyStatus,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };