/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'propertyId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'featured' : boolean,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'area' : bigint,
  'description' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
}
export type PropertyStatus = { 'sold' : null } |
  { 'available' : null };
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null };
export interface _SERVICE {
  'addProperty' : ActorMethod<
    [
      string,
      PropertyType,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      boolean,
    ],
    bigint
  >,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getPropertiesByStatus' : ActorMethod<[PropertyStatus], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[PropertyType], Array<Property>>,
  'getPropertyById' : ActorMethod<[bigint], Property>,
  'searchProperties' : ActorMethod<
    [string, [] | [PropertyType], [] | [bigint], [] | [bigint]],
    Array<Property>
  >,
  'seedProperties' : ActorMethod<[], undefined>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    bigint
  >,
  'updateProperty' : ActorMethod<
    [
      bigint,
      string,
      PropertyType,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      PropertyStatus,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];