/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: bigint;
    status: PropertyStatus;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    area: bigint;
    description: string;
    bathrooms: bigint;
    price: bigint;
    location: string;
}
export interface Enquiry {
    id: bigint;
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export enum PropertyStatus {
    sold = "sold",
    available = "available"
}
export enum PropertyType {
    commercial = "commercial",
    villa = "villa",
    plot = "plot",
    apartment = "apartment"
}
export interface backendInterface {
    addProperty(title: string, propertyType: PropertyType, location: string, price: bigint, bedrooms: bigint, bathrooms: bigint, area: bigint, description: string, featured: boolean): Promise<bigint>;
    deleteProperty(id: bigint): Promise<void>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllProperties(): Promise<Array<Property>>;
    getPropertiesByStatus(status: PropertyStatus): Promise<Array<Property>>;
    getPropertiesByType(propertyType: PropertyType): Promise<Array<Property>>;
    getPropertyById(id: bigint): Promise<Property>;
    searchProperties(location: string, propertyType: PropertyType | null, minPrice: bigint | null, maxPrice: bigint | null): Promise<Array<Property>>;
    seedProperties(): Promise<void>;
    submitEnquiry(name: string, email: string, phone: string, message: string, propertyId: bigint | null): Promise<bigint>;
    updateProperty(id: bigint, title: string, propertyType: PropertyType, location: string, price: bigint, bedrooms: bigint, bathrooms: bigint, area: bigint, description: string, status: PropertyStatus, featured: boolean): Promise<void>;
}
import type { Enquiry as _Enquiry, Property as _Property, PropertyStatus as _PropertyStatus, PropertyType as _PropertyType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProperty(arg0: string, arg1: PropertyType, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: string, arg8: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(arg0, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(arg0, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByStatus(arg0: PropertyStatus): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByStatus(to_candid_PropertyStatus_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByStatus(to_candid_PropertyStatus_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByType(arg0: PropertyType): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByType(to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByType(to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyById(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyById(arg0);
                return from_candid_Property_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyById(arg0);
            return from_candid_Property_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProperties(arg0: string, arg1: PropertyType | null, arg2: bigint | null, arg3: bigint | null): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProperties(arg0, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProperties(arg0, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedProperties(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProperties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProperties();
            return result;
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateProperty(arg0: bigint, arg1: string, arg2: PropertyType, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string, arg9: PropertyStatus, arg10: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, arg1, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PropertyStatus_n14(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, arg1, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PropertyStatus_n14(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
}
function from_candid_Enquiry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    propertyId: [] | [bigint];
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: bigint;
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        propertyId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.propertyId)),
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PropertyStatus;
    title: string;
    featured: boolean;
    propertyType: _PropertyType;
    bedrooms: bigint;
    area: bigint;
    description: string;
    bathrooms: bigint;
    price: bigint;
    location: string;
}): {
    id: bigint;
    status: PropertyStatus;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    area: bigint;
    description: string;
    bathrooms: bigint;
    price: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_PropertyStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        featured: value.featured,
        propertyType: from_candid_PropertyType_n12(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        area: value.area,
        description: value.description,
        bathrooms: value.bathrooms,
        price: value.price,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
}): PropertyStatus {
    return "sold" in value ? PropertyStatus.sold : "available" in value ? PropertyStatus.available : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    villa: null;
} | {
    plot: null;
} | {
    apartment: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "villa" in value ? PropertyType.villa : "plot" in value ? PropertyType.plot : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PropertyStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): _PropertyStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType | null): [] | [_PropertyType] {
    return value === null ? candid_none() : candid_some(to_candid_PropertyType_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): {
    sold: null;
} | {
    available: null;
} {
    return value == PropertyStatus.sold ? {
        sold: null
    } : value == PropertyStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    villa: null;
} | {
    plot: null;
} | {
    apartment: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
